SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `bd_biblio`.`tpreferences` (
  `codepreferences` INT(11) NOT NULL,
  `nomEntreprise` VARCHAR(45) NOT NULL,
  `nomContact` VARCHAR(45) NOT NULL,
  `courriel` VARCHAR(45) NOT NULL,
  `telephone` INT(11) NOT NULL,
  `commentaire` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`codepreferences`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;